# -*- coding: utf-8 -*-
"""Cenyongyi_Sang_Lab3DataAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLkrntUH8PHYc4y4tLKF49eBHc8nuBYD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import scipy.stats as stats

url = 'https://vincentarelbundock.github.io/Rdatasets/csv/openintro/satgpa.csv'
df = pd.read_csv(url)

df.head()

df['fy_gpa'].describe()

#Students' first year GPA in college, dependent variable

df['hs_gpa'].describe()

#Students' overall GPA during high school, independent variable

#I expect there is a strong relationship where a higher high school GPA is a
#reflection of better learning capabilities that should translate into students'
#academic performance in college

hs_universityfy = smf.ols(formula = 'fy_gpa~hs_gpa',
                          data = df, subset=df['sat_sum'].notna()).fit()
print(hs_universityfy.summary())

#Coefficient for first year GPA in college is 0.7431, meaning that for each
#additional +1 GPA in high school, the student is also likely to perform better
#in his/her first year in college that the GPA increases by 0.7431.
#The model is statistically significant with p < 0.001. However, the R-squared
#of 0.295 indicates that only about 30 percent of the data is explained by this
#relationship, which is considerable but doesn't indicate a strong association.

df['sat_sum'].describe()

df_filtered = df[['hs_gpa','sat_sum']].dropna()
stats.pearsonr(df_filtered['hs_gpa'],df_filtered['sat_sum'])

#The two independent variables correlate meaningfully (+0.43)
#Students with higher high school GPA tend to have higher SAT scores

hs_actual_fy = smf.ols(formula='fy_gpa~ hs_gpa + sat_sum',data = df).fit()
print(hs_actual_fy.summary())

#High School GPA has a coefficient of 0.57, indicating that 1 point increase of
#it is associated with an increase of 0.57 in student first year GPA in college.
#SAT score has a coefficient of 0.01, indiciating that 1 point increase of it is
#associated with an increase of 0.01 in the student's first year GPA in college.
#Although the number doesn't look big, cosniderting the mean value for sat_sum
#is 103 and max value is 144, it means that a student scores 1400 in SAT will
#likely to have a 0.2 point better GPA than a student scores 1200 in SAT.
#Both p values are <0.001 which means they are statistically significant
#The adjusted R-squared is 0.357, which is stronger than the value 0.295 in the
#ealier model, it increases the predictive accuracy of the model considerablly
#and makes it much stronger.
#This result proves that having two standard measurement of students' academic
#capabilities are likely to predict their performance after they entered college

df['sat_v_rank'] = df['sat_v'].rank(ascending = False)
df['sat_m_rank'] = df['sat_m'].rank(ascending = False)

extreme_comb = df[['rownames','sex','sat_v_rank','sat_m_rank']].copy()
extreme_comb['rank_difference'] = extreme_comb['sat_v_rank'] - extreme_comb['sat_m_rank']
extreme_sorted = extreme_comb.sort_values(by = 'rank_difference', ascending = False).head(5)

extreme_sorted

df['sat_v_rank'] = df['sat_v'].rank(ascending = False)
df['sat_m_rank'] = df['sat_m'].rank(ascending = False)

extreme_comb = df[['rownames','sex','sat_v_rank','sat_m_rank','fy_gpa']].copy()
extreme_comb['rank_difference'] = extreme_comb['sat_v_rank'] - extreme_comb['sat_m_rank']
extreme_sorted = extreme_comb.sort_values(by = 'rank_difference', ascending = False).head(10)

extreme_sorted

#Unfortunately I should find a better dataset with more indications
#But here I'm just playing with it a little bit. I find the top 5 and
#then top 10 test takers with biggest gaps between their verbal
#and math sections. I also added sex and college first year GPA into
#the new subset. 5 of the top 6 on the list are males, does it mean
#that male students are usually better on math but weaker on their
#verbal skills? Also none of these studens' GPA are above 2.8 and since
#the 50th percentile of fy_gpa is 2.465, most of them are the bottom
#half of this data sample, does that mean students with academic imbalance
#would struggle more when they entered the college?# Modified by Helle
